PACKAGE_NAME="aic8800dc"
PACKAGE_VERSION="6.4.3.0-patched.1"

BUILT_MODULE_NAME[0]="aic_load_fw"
BUILT_MODULE_LOCATION[0]="drivers/aic8800/aic_load_fw/"
DEST_MODULE_LOCATION[0]="/updates/"

BUILT_MODULE_NAME[1]="aic8800_fdrv"
BUILT_MODULE_LOCATION[1]="drivers/aic8800/aic8800_fdrv/"
DEST_MODULE_LOCATION[1]="/updates/"

MAKE="make -C drivers/aic8800 KDIR=${kernel_source_dir}"
CLEAN="make -C drivers/aic8800 clean"

AUTOINSTALL="yes"
